# Generated by Django 2.2 on 2020-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('roll', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('std_class', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
