# Generated by Django 2.2 on 2020-06-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='std_class',
        ),
    ]
